name = "docgram"
compatibility_date = "2025-05-15"

[site]
bucket = "./dist"
entry-point = "."# Adjust test configuration at 2024-10-18 14:16:11 - 6002
# Adjust test configuration at 2024-10-20 13:25:49 - 25181
# Update entry-point at 2024-10-22 13:50:29 - 18442
